name: GitHub Streak Saver

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC (which is 8:30 AM IST)
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp file
        run: |
          # Get current time in IST (Asia/Kolkata)
          echo "Last updated: $(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S %Z')" > update.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add update.txt
          git commit -m "Auto commit: $(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S %Z')"
          git push
